### ISSUE TITLE
DecisionTreeClassifier producing strange results after upgrade

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJ.jl#319] opened 2019-11-04 23:02 UTC
**Describe the bug**
The fit/predict workflow is producing strange results after upgrading to the latest stable MLJ.jl

**To Reproduce**
Assume you have two data sets: train.csv and test.csv. The goal is to train a decision tree to classify the `crop` column based on the `band1, ..., band4` columns.

First, we load the data, which is attached to this bug report:

```julia
using CSV, CategoricalArrays

train = CSV.read("train.csv")
test  = CSV.read("test.csv")

# fix label type for classification
train.crop = categorical(train.crop)
test.crop = categorical(test.crop)

# define feature and label arrays
Xtrain = train[[:band1,:band2,:band3,:band4]]
Xtest  = test[[:band1,:band2,:band3,:band4]]
ytrain = train[:crop]
```

Then, we load a decision tree classifier and compute the confusion matrix:

```julia
using MLJ, MLJBase

@load DecisionTreeClassifier

model = DecisionTreeClassifier()

# fit/predict workflow
θ, _, __ = MLJBase.fit(model, 0, Xtrain, ytrain)
probs = MLJBase.predict(model, θ, Xtest)

ytest = test[:crop]
ŷtest = mode.(probs)

y = get.(ytest)
ŷ = get.(ŷtest)

C = zeros(3,3)
for i in 1:length(y)
    C[y[i],ŷ[i]] += 1
end

C

3×3 Array{Float64,2}:
  10.0  170.0   29.0
  67.0   44.0  755.0
 371.0   14.0   50.0
```

We can observe that the decision tree is somehow "flipping" the categories in the prediction. I also plotted the data (in this case it is spatial) and noticed the colours were flipped:

<img width="592" alt="Screen Shot 2019-11-04 at 19 40 42" src="https://user-images.githubusercontent.com/3345261/68164317-4e1a2380-ff3b-11e9-8ef6-063a957440cb.png">
<img width="613" alt="Screen Shot 2019-11-04 at 19 40 52" src="https://user-images.githubusercontent.com/3345261/68164328-51adaa80-ff3b-11e9-8414-a4f23a890714.png">

**Expected behavior**
In previous releases (or at least before I did the upgrade to the latest stable MLJ.jl stack), the code above wouldn't produce such confusion matrix. The decision tree is not tuned, I understand that, but the confusion matrix seems incorrect.

**Additional context**
I am running on Julia v1.2 with the latest stable release of the project. Below you can find the exact versions I am using.

**Versions**
- MLJ v0.5.2
- MLJBase v0.7.3
- MLJModels v0.5.5
- DecisionTree v0.9.1

I appreciate if you can take a look at this issue. I spent a great amount of time trying to debug it without success.

Link to the data: https://gist.github.com/juliohm/72eb5f1555e337fafa031791ced63d09

**Comment by ablaom** [comment] 2019-11-04 23:21
@juliohm Thanks for reporting and also investigating this issue. 

A MWE would certainly speed up the process, but I understand this takes some work. 

One thing to settle is whether this is because of recent changes to DecisionTree.jl of some change in our glue code.  Do you get the same behaviour if you pin DecisionTree.jl to DecisionTree@0.8.4?

**Comment by juliohm** [comment] 2019-11-04 23:47
Thank you @ablaom , I will try to produce a MWE with a smaller data set. In the meantime, I can confirm that DecisionTree.jl v0.8.4 has the same behaviour.

Do you have pointers for the glue code you mentioned? Does it live in DecisionTree.jl or MLJModels.jl, or somewhere else?

**Comment by ablaom** [comment] 2019-11-05 00:38
Thanks @juliohm. I have a made a guess about what the problem is and have addressed it at [MLJModels#treebug](https://github.com/alan-turing-institute/MLJModels.jl/tree/treebug). Can you confirm if this fixes your issue?

In any case, we should add a MWE to the tests, so that will be extremely valuable, thanks.

The glue code lives here: https://github.com/alan-turing-institute/MLJModels.jl/blob/treebug/src/DecisionTree.jl

**Comment by juliohm** [comment] 2019-11-05 12:01
I confirm that the issue is fixed @ablaom on the branch you shared above. Could you please patch and release a new version of MLJModels.jl? Thank you for your time and quick fix. :)

**Comment by juliohm** [comment] 2019-11-05 12:12
I have also updated the gist with a smaller version of the dataset to help creating the test case. The new files are `small-train.csv` and `small-test.csv`. I am positive that we can decrease the dataset further and still reproduce the issue. Can try to do that over the week.

**Comment by ablaom** [comment] 2019-11-05 22:28
Resolved in this release https://github.com/alan-turing-institute/MLJModels.jl/releases/tag/v0.5.6

**Closed by ablaom** 2019-11-05 22:28 UTC
