### ISSUE TITLE
transformations like in R with formulas `y ~ a + a * b + b^3`.

### ISSUE THREAD

**Issue by vollmersj** [alan-turing-institute/MLJ.jl#867] opened 2021-11-22 21:39 UTC
**Is your feature request related to a problem? Please describe.**
This would make code more easy readable.
**Describe the solution you'd like**
One could use  StatsModels.jl `@formula`?

**Comment by ablaom** [comment] 2021-11-22 21:44
Thanks. This is however a duplicate of https://github.com/JuliaAI/MLJModels.jl/issues/406

**Closed by ablaom** 2021-11-22 21:44 UTC
