### ISSUE TITLE
Get Started Examples doesn't work on MLJ 0.5.2

### ISSUE THREAD

**Issue by xiaodaigh** [alan-turing-institute/MLJ.jl#324] opened 2019-11-09 13:12 UTC
```julia
using RDatasets, DataFrames
iris = dataset("datasets", "iris")

using MLJ

y, X = unpack(iris, ==(:Species), colname -> true);
tree_model = @load DecisionTreeClassifier verbosity=1

evaluate(tree_model, X, y,
                resampling=CV(shuffle=true), measure=cross_entropy, verbosity=0)

tree = machine(tree_model, X, y)
```

I just get error

```julia-repl

 Info: A model type "DecisionTreeClassifier" is already loaded. 
│ No new code loaded. 
└ @ MLJModels C:\Users\RTX2080\.julia\packages\MLJModels\5Qzge\src\loading.jl:43
MethodError: no method matching machine(::DecisionTreeClassifier, ::DataFrame, ::CategoricalArray{String,1,UInt8,String,CategoricalString{UInt8},Union{}})
Closest candidates are:
  machine(!Matched::M<:MLJBase.Model, ::Any...) where M<:MLJBase.Model at C:\Users\RTX2080\.julia\packages\MLJ\BEVGY\src\machines.jl:28
  machine(!Matched::MLJBase.Model, ::Any, !Matched::AbstractNode) at C:\Users\RTX2080\.julia\packages\MLJ\BEVGY\src\networks.jl:433
  machine(!Matched::MLJBase.Model, !Matched::AbstractNode, ::Any) at C:\Users\RTX2080\.julia\packages\MLJ\BEVGY\src\networks.jl:434

Stacktrace:
 [1] top-level scope at In[66]:5
]
```

**Comment by ablaom** [comment] 2019-11-10 19:38
Thanks for reporting.

I am unable to reproduce. Here's my setting:

```julia
julia> using Pkg; Pkg.status()
    Status `~/.julia/environments/junk/Project.toml`
  [7806a523] DecisionTree v0.9.1
  [add582a8] MLJ v0.5.2
  [d491faf4] MLJModels v0.5.6
  [ce6b1742] RDatasets v0.6.4

julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc (2019-05-16 04:10 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PATH = /Applications/Julia-1.1.app/Contents/Resources/julia/bin/julia
```

Can you please provide similar detail?

**Comment by xiaodaigh** [comment] 2019-11-10 22:59
I can't reproduce on my Linux box at work either. So hopefully it's not a Windows thing.

Confirmed to work on 

```julia
versioninf()

Julia Version 1.3.0-rc3.0
Commit b5ccd0f2ef (2019-10-04 01:57 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i9-9900X CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 20
```

**Comment by tlienart** [comment] 2019-11-11 08:12
I'll close this then, please re-open a new issue with MWE if you encounter further problems, thanks!

**Closed by tlienart** 2019-11-11 08:12 UTC
