### ISSUE TITLE
Task Design?

### ISSUE THREAD

**Issue by kirtsar** [alan-turing-institute/MLJ.jl#96] opened 2019-03-04 19:34 UTC
What should the Task do?
my vision of working with `Task` object is something like:
assume that we have some data for supervised learning: X, y. X and y can be any reasonable type (X is Matrix, DataFrame, ...; y is some subtype of AbstractVector).

```task = Task(data = X, target = y, goal = SomeGoal(optional args) )```

where SomeGoal is something from (for example):
1. Binary(is proba = true/false)
2. Multiclass(is proba = true/false)
3. Regression(is proba = true/false)
Based on the type of the task, the output for X_and_y should be appropriate (Continuous, discrete, ...)

**Comment by ablaom** [comment] 2019-03-04 22:47
Sorry, closing as duplicate of [#68](https://github.com/alan-turing-institute/MLJ.jl/issues/68).

**Closed by ablaom** 2019-03-04 22:47 UTC
