### ISSUE TITLE
MLJ regression model errors

### ISSUE THREAD

**Issue by azev77** [alan-turing-institute/MLJ.jl#401] opened 2019-12-15 01:36 UTC
**Describe the bug**

I tried every MLJ regression model on the Boston Housing data. The following didn't work: 

**To Reproduce**

```julia
using Pkg; Pkg.activate("."); Pkg.instantiate();
using RDatasets, MLJ, Statistics, PrettyPrinting, GLM

X, y =  @load_boston; 
train, test = 1:406, 407:506 

#For example here is one that worked
reg = @load ARDRegressor;
m = machine(reg, X, y);
fit!(m, rows=train);
ŷ = predict(m, rows=test)
os_ARDRegressor = rms(ŷ , y[test])

# Below are the four that did not work
reg = @load LADRegressor;
m = machine(reg, X, y);
fit!(m, rows=train);
#TypeError: in keyword argument solver, expected MLJLinearModels.Solver, got Nothing
 
reg = @load QuantileRegressor;
m = machine(reg, X, y);
fit!(m, rows=train);
#TypeError: in keyword argument solver, expected MLJLinearModels.Solver, got Nothing

reg = @load RobustRegressor;
m = machine(reg, X, y);
fit!(m, rows=train);
#TypeError: in keyword argument solver, expected MLJLinearModels.Solver, got Nothing


reg = @load LassoCVRegressor;
m = machine(reg, X, y);
#MethodError: no method matching machine(...)

#Also the following 
@load HuberRegressor pkg= MLJLinearModels;
@load HuberRegressor pkg= ScikitLearn;

#You're right! After I updated MLJ & ScikitLearn, HuberRegressor works




```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by tlienart** [comment] 2019-12-23 17:29
Thanks for reporting this! this is a simple issue with the  interface of MLJLinearModels in MLJModels.jl which I'll fix asap.

Note  that

* `HuberRegressor` from `ScikitLearn` works:

```julia
julia> @load HuberRegressor pkg=ScikitLearn
[ Info: Precompiling ScikitLearn [3646fa90-6ef7-5e7e-9f22-8aca16db6324]
HuberRegressor(epsilon = 1.35,
               max_iter = 100,
               alpha = 0.0001,
               warm_start = false,
               fit_intercept = true,
               tol = 1.0e-5,) @ 9…19

julia> fit!(mach)^C

julia> m = machine(HuberRegressor(), X, y);

julia> fit!(m, rows=train)
[ Info: Training Machine{HuberRegressor} @ 3…82.
Machine{HuberRegressor} @ 3…82
```

* ARDRegressor is also from ScikitLearn

MLJLinearModels (and its interface) are still fairly experimental at  this point. But thanks a lot for reporting, I'll write here when the issue is fixed.

**Comment by tlienart** [comment] 2019-12-26 12:22
The issue is now fixed with MLJLinearModels 0.2.3. If you do

```julia-repl
(v1.x) pkg> up MLJLinearModels
```

and subsequently 

```julia

julia> using MLJ
[ Info: Precompiling MLJ [add582a8-e3ab-11e8-2d5e-e98b27df1bc7]
[ Info: Model metadata loaded from registry. 

julia> X, y =  @load_boston;

julia> train, test = 1:406, 407:506 
(1:406, 407:506)

julia> reg = @load LADRegressor;

[ Info: Precompiling MLJLinearModels [6ee0df7b-362f-4a72-a706-9e79364fb692]

julia> m = machine(reg, X, y);

julia> fit!(m, rows=train);
[ Info: Training Machine{LADRegressor} @ 1…12.

julia> fitted_params(m).coefs
12-element Array{Float64,1}:
 -0.17686712971246232 
  0.06109745466098378 
 -0.06638979102134852 
  0.26445385485930745 
  6.15291904135371    
 -0.04664090979468351 
 -1.385610269130155   
  0.24826050814779696 
 -0.014997734899042822
 -0.3293365498583088  
  0.012247768779959404
 -0.23984043927317733 
```

The issue was that for RobustLoss a default solver was not properly defined. Thanks again for reporting.

**Comment by azev77** [comment] 2019-12-26 18:18
```
#I get an error @ the fit!() command
using MLJ
X, y =  @load_boston;
train, test = 1:406, 407:506
reg = @load LADRegressor;
m = machine(reg, X, y);
fit!(m, rows=train);

```
Error: Not yet implemented
└ @ MLJLinearModels C:\Users\azevelev\.julia\packages\MLJLinearModels\nEQIy\src\fit\default.jl:23
ERROR: TypeError: in keyword argument solver, expected MLJLinearModels.Solver, got Nothing

**Comment by tlienart** [comment] 2019-12-26 23:11
Ok that shouldn't be the case. Would you mind sending me the  `status`? 

Here's what I just tried a minute ago with 1.3:

```
# mkdir testMLJ && cd testMLJ
(v1.3) pkg> activate .
(testMLJ) pkg> add MLJ MLJLinearModels
(testMLJ) pkg> status
    Status `~/Desktop/tjd/testMLJ/Project.toml`
  [add582a8] MLJ v0.6.0
  [6ee0df7b] MLJLinearModels v0.2.3
julia> using MLJ

julia> X, y =  @load_boston;

julia> train, test = 1:406, 407:506
(1:406, 407:506)

julia> reg = @load LADRegressor;

julia> m = machine(reg, X, y);

julia> fit!(m, rows=train);
[ Info: Training Machine{LADRegressor} @ 8…85.

julia> fitted_params(m).coefs
12-element Array{Float64,1}:
 -0.17686712971246232 
  0.06109745466098378 
 -0.06638979102134852 
  0.26445385485930745 
  6.15291904135371    
 -0.04664090979468351 
 -1.385610269130155   
  0.24826050814779696 
 -0.014997734899042822
 -0.3293365498583088  
  0.012247768779959404
 -0.23984043927317733
```

**Comment by azev77** [comment] 2019-12-27 18:53
Here is what I have, but getting MLJLinearModels to work isn't a big priority right now. 

┌ Error: Not yet implemented
└ @ MLJLinearModels C:\Users\azevelev\.julia\packages\MLJLinearModels\nEQIy\src\fit\default.jl:23
(v1.3) pkg> status
    Status `C:\Users\azevelev\.julia\environments\v1.3\Project.toml`
  [c52e3926] Atom v0.11.3
  [6e4b80f9] BenchmarkTools v0.4.3
  [631607c0] CMake v1.1.2
  [336ed68f] CSV v0.5.18
  [98729d58] ContinuousTransformations v1.0.0
  [667455a9] Cubature v1.4.1
  [a93c6f00] DataFrames v0.20.0
  [7806a523] DecisionTree v0.10.0
  [b4f34e82] Distances v0.8.2
  [31c24e10] Distributions v0.21.11
  [f6006082] EvoTrees v0.3.0
  [38e38edf] GLM v1.3.5
  [c91e804a] Gadfly v1.0.1
  [5b3bc22e] GlobalSearchRegression v1.0.4
  [7073ff75] IJulia v1.20.2
  [43edad99] InstantiateFromURL v0.3.3
  [c601a237] Interact v0.10.3
  [a98d9a8b] Interpolations v0.12.5
  [033835bb] JLD2 v0.1.9
  [682c06a0] JSON v0.21.0
  [e5e0dc1b] Juno v0.7.2
  [b1bec4e5] LIBSVM v0.4.0
  [38d8eb38] Lathe v0.0.3
  [5078a376] LazyArrays v0.14.10
  [add582a8] MLJ v0.5.9
  [a7f614a8] MLJBase v0.8.4
  [cb937e20] MLJJLBoost v0.1.1
  [6ee0df7b] MLJLinearModels v0.2.1
  [d491faf4] MLJModels v0.5.9
  [dbb5928d] MappedArrays v0.2.2
  [6f286f6a] MultivariateStats v0.7.0
  [76087f3c] NLopt v0.5.1
  [2774e3e8] NLsolve v4.2.0
  [9bbee03b] NaiveBayes v0.4.0
  [b8a86587] NearestNeighbors v0.4.4
  [429524aa] Optim v0.19.7
  [f5f7c340] PATHSolver v0.5.2
  [d96e819e] Parameters v0.12.0
  [91a5bcdd] Plots v0.28.3
  [54e16d92] PrettyPrinting v0.2.0
  [d330b81b] PyPlot v2.8.2
  [fcd29c91] QuantEcon v0.16.2
  [ce6b1742] RDatasets v0.6.6
  [321657f4] ScientificTypes v0.2.7
  [3646fa90] ScikitLearn v0.5.1
  [7ccca996] SimpleDifferentialOperators v0.6.1
  [90137ffa] StaticArrays v0.12.1
  [2913bbd2] StatsBase v0.32.0
  [fd094767] Suppressor v0.1.1
  [198dc43e] TSML v2.4.3
  [bd369af6] Tables v0.2.11
  [1d978283] TensorFlow v0.11.0
  [009559a3] XGBoost v0.4.2
  [10745b16] Statistics

(v1.3) pkg>

**Comment by tlienart** [comment] 2019-12-27 21:43
> Here is what I have, but getting MLJLinearModels to work isn't a big priority right now.

Sure I understand
 
> ┌ Error: Not yet implemented
> └ @ MLJLinearModels C:\Users\azevelev.julia\packages\MLJLinearModels\nEQIy\src\fit\default.jl:23
> (v1.3) pkg> status
> ... 
> [6ee0df7b] MLJLinearModels v0.2.1

Ok so that's not the latest version, the issue was fixed on `0.2.3` , and currently the version is  `0.2.4`. That's the  problem.

I'll close the issue for now but re-open if you do update and still can't get things to work with the same error (or open an issue directly at MLJLinearModels). Thanks!

**Closed by tlienart** 2019-12-27 21:43 UTC
Labels: WIP, done

**Comment by azev77** [comment] 2019-12-28 01:11
@tlienart For what it's worth neither MLJ nor MLJLinearModels are updating to their latest versions.

**Comment by azev77** [comment] 2019-12-29 21:13
@tlienart I wasn't able to update MLJ or MLJLinear models so I manually deleted those files. After I reinstalled them everything from MLJLinearModels works! 

The only model that still doesn't work is: 
```Julia
reg = @load LassoCVRegressor;
m = machine(reg, X, y);
#MethodError: no method matching machine(...)
```

**Comment by tlienart** [comment] 2019-12-29 21:30
Thanks a lot, actually  there's a small mistake in  the interface of `LassoCV` which prevents the constructor from working properly because `random_state` is improperly  typed to  `Int` where it  needed to be  typed as `Any`, I'll fix this asap.
