### ISSUE TITLE
CURANDError: kernel launch failure (code 201, CURAND_STATUS_LAUNCH_FAILURE)

### ISSUE THREAD

**Issue by MrBenzWorld** [alan-turing-institute/MLJ.jl#997] opened 2022-12-27 11:37 UTC
using MLJ
using EvoTrees

EvoTreeRegressor = @load EvoTreeRegressor verbosity=0

model = EvoTreeRegressor ()

ERROR: CURANDError: kernel launch failure (code 201, CURAND_STATUS_LAUNCH_FAILURE)

it is not working on CPU.  Please fix it. 
itis not working on Julia 1.8.4 , EvoTrees v0.14.3

**Comment by ablaom** [comment] 2022-12-28 15:10
Thanks for reporting. Unfortunately I cannot reproduce. My setup:

```julia
Status `/private/var/folders/4n/gvbmlhdc8xj973001s6vdyw00000gq/T/jl_zOGjH0/Project.toml`
⌃ [f6006082] EvoTrees v0.14.3
  [add582a8] MLJ v0.19.0
Info Packages marked with ⌃ have new versions available and may be upgradable.

julia> versioninfo()
Julia Version 1.8.4
Commit 00177ebc4fc (2022-12-23 21:32 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 12 × Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 5 on 12 virtual cores
Environment:
  JULIA_LTS_PATH = /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia
  JULIA_PATH = /Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia
  JULIA_EGLOT_PATH = /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia
  JULIA_NUM_THREADS = 5
  DYLD_LIBRARY_PATH = /usr/local/homebrew/Cellar/libomp/9.0.1/lib/
  JULIA_NIGHTLY_PATH = /Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia
```

@jeremiedb Any idea what this might be? Can you reproduce?
@OkonSamuel Can you reproduce?

@MrBenzWorld Can you please report the output of `infoversion()`?

**Comment by ablaom** [comment] 2022-12-28 15:12
Closed as duplicate of https://github.com/Evovest/EvoTrees.jl/issues/203

**Closed by ablaom** 2022-12-28 15:12 UTC
