### ISSUE TITLE
LoadError: UndefVarError: refcode not defined

### ISSUE THREAD

**Issue by polmonroig** [alan-turing-institute/MLJ.jl#782] opened 2021-05-02 09:50 UTC
**Description**
Every time I call a MLJ function such as `fit!`, `evaluate` or when I run `test MLJ`. I am getting the error 

`LoadError: UndefVarError: refcode not defined`

The bug happens at different times, by this I mean that when I run the test I am getting this error 
```julia
     Testing Running tests...
Test Summary: | Pass  Total
version       |    2      2
Test Summary:  | Pass  Total
exported_names |    3      3
ensembles: Error During Test at /home/pol/.julia/packages/MLJ/o2pDW/test/runtests.jl:20
  Test threw exception
  Expression: include("ensembles.jl")
  LoadError: UndefVarError: refcode not defined
  Stacktrace:
    [1] getproperty
      @ ./Base.jl:26 [inlined]
    [2] int(#unused#::MLJModelInterface.FullInterface, x::CategoricalArrays.CategoricalValue{Char, UInt32})
      @ MLJBase ~/.julia/packages/MLJBase/swtDd/src/interface/data_utils.jl:22
    [3] int(x::CategoricalArrays.CategoricalValue{Char, UInt32}; type::Nothing)
      @ MLJModelInterface ~/.julia/packages/MLJModelInterface/MqreB/src/data_utils.jl:73
    [4] int(x::CategoricalArrays.CategoricalValue{Char, UInt32})
      @ MLJModelInterface ~/.julia/packages/MLJModelInterface/MqreB/src/data_utils.jl:73
    [5] (::MLJBase.var"#24#25"{LittleDict{CategoricalArrays.CategoricalValue{Char, UInt32}, Float64, Vector{CategoricalArrays.CategoricalValue{Char, UInt32}}, Vector{Float64}}})(c::CategoricalArrays.CategoricalValue{Char, UInt32})
      @ MLJBase ./none:0
    [6] iterate
      @ ./generator.jl:47 [inlined]
    [7] collect(itr::Base.Generator{CategoricalArrays.CategoricalVector{Char, UInt32, Char, CategoricalArrays.CategoricalValue{Char, UInt32}, Union{}}, MLJBase.var"#24#25"{LittleDict{CategoricalArrays.CategoricalValue{Char, UInt32}, Float64, Vector{CategoricalArrays.CategoricalValue{Char, UInt32}}, Vector{Float64}}}})
      @ Base ./array.jl:678
    [8] UnivariateFinite(::MLJModelInterface.FullInterface, prob_given_class::LittleDict{CategoricalArrays.CategoricalValue{Char, UInt32}, Float64, Vector{CategoricalArrays.CategoricalValue{Char, UInt32}}, Vector{Float64}}; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ MLJBase ~/.julia/packages/MLJBase/swtDd/src/univariate_finite/types.jl:143
    [9] UnivariateFinite(::MLJModelInterface.FullInterface, prob_given_class::LittleDict{CategoricalArrays.CategoricalValue{Char, UInt32}, Float64, Vector{CategoricalArrays.CategoricalValue{Char, UInt32}}, Vector{Float64}})
      @ MLJBase ~/.julia/packages/MLJBase/swtDd/src/univariate_finite/types.jl:127
   [10] _UnivariateFinite(support::CategoricalArrays.CategoricalVector{Char, UInt32, Char, CategoricalArrays.CategoricalValue{Char, UInt32}, Union{}}, probs::Vector{Float64}, N::Int64; augment::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ MLJBase ~/.julia/packages/MLJBase/swtDd/src/univariate_finite/types.jl:246
   [11] #_UnivariateFinite#36
      @ ~/.julia/packages/MLJBase/swtDd/src/univariate_finite/types.jl:297 [inlined]
   [12] _UnivariateFinite
      @ ~/.julia/packages/MLJBase/swtDd/src/univariate_finite/types.jl:297 [inlined]
   [13] UnivariateFinite(::MLJModelInterface.FullInterface, support::CategoricalArrays.CategoricalVector{Char, UInt32, Char, CategoricalArrays.CategoricalValue{Char, UInt32}, Union{}}, probs::Vector{Float64}; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ MLJBase ~/.julia/packages/MLJBase/swtDd/src/univariate_finite/types.jl:214
   [14] UnivariateFinite
      @ ~/.julia/packages/MLJBase/swtDd/src/univariate_finite/types.jl:203 [inlined]
   [15] UnivariateFinite(support::CategoricalArrays.CategoricalVector{Char, UInt32, Char, CategoricalArrays.CategoricalValue{Char, UInt32}, Union{}}, probs::Vector{Float64}; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ MLJModelInterface ~/.julia/packages/MLJModelInterface/MqreB/src/data_utils.jl:431
   [16] UnivariateFinite(support::CategoricalArrays.CategoricalVector{Char, UInt32, Char, CategoricalArrays.CategoricalValue{Char, UInt32}, Union{}}, probs::Vector{Float64})
      @ MLJModelInterface ~/.julia/packages/MLJModelInterface/MqreB/src/data_utils.jl:431
   [17] UnivariateFinite(::CategoricalArrays.CategoricalVector{Char, UInt32, Char, CategoricalArrays.CategoricalValue{Char, UInt32}, Union{}}, ::Vararg{Any, N} where N; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ MLJBase ~/.julia/packages/MLJBase/swtDd/src/univariate_finite/types.jl:32
   [18] UnivariateFinite(::CategoricalArrays.CategoricalVector{Char, UInt32, Char, CategoricalArrays.CategoricalValue{Char, UInt32}, Union{}}, ::Vararg{Any, N} where N)
      @ MLJBase ~/.julia/packages/MLJBase/swtDd/src/univariate_finite/types.jl:32
   [19] top-level scope
      @ ~/.julia/packages/MLJ/o2pDW/test/ensembles.jl:47
   [20] include(fname::String)
      @ Base.MainInclude ./client.jl:444
   [21] macro expansion
      @ ~/.julia/packages/MLJ/o2pDW/test/runtests.jl:20 [inlined]
   [22] macro expansion
      @ /build/julia/src/julia-1.6.1/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [23] top-level scope
      @ ~/.julia/packages/MLJ/o2pDW/test/runtests.jl:20
  in expression starting at /home/pol/.julia/packages/MLJ/o2pDW/test/ensembles.jl:1
Test Summary: | Pass  Error  Total
ensembles     |    4      1      5
ERROR: LoadError: Some tests did not pass: 4 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /home/pol/.julia/packages/MLJ/o2pDW/test/runtests.jl:19
ERROR: Package MLJ errored during testing
```
when I run fit!

```julia
[ Info: Training Machine{DecisionTreeClassifier,…} @969.
┌ Error: Problem fitting the machine Machine{DecisionTreeClassifier,…} @969.
└ @ MLJBase ~/.julia/packages/MLJBase/swtDd/src/machines.jl:472
[ Info: Running type checks...
[ Info: Type checks okay.
ERROR: UndefVarError: refcode not defined
Stacktrace:
  [1] getproperty
    @ ./Base.jl:26 [inlined]
  [2] int(#unused#::MLJModelInterface.FullInterface, x::CategoricalArrays.CategoricalValue{String, UInt8})
    @ MLJBase ~/.julia/packages/MLJBase/swtDd/src/interface/data_utils.jl:22
  [3] int(x::CategoricalArrays.CategoricalValue{String, UInt8}; type::Nothing)
    @ MLJModelInterface ~/.julia/packages/MLJModelInterface/MqreB/src/data_utils.jl:73
  [4] int(x::CategoricalArrays.CategoricalValue{String, UInt8})
    @ MLJModelInterface ~/.julia/packages/MLJModelInterface/MqreB/src/data_utils.jl:73
  [5] _broadcast_getindex_evalf
    @ ./broadcast.jl:648 [inlined]
  [6] _broadcast_getindex
    @ ./broadcast.jl:621 [inlined]
  [7] getindex
    @ ./broadcast.jl:575 [inlined]
  [8] copy
    @ ./broadcast.jl:922 [inlined]
  [9] materialize
    @ ./broadcast.jl:883 [inlined]
 [10] int(#unused#::MLJModelInterface.FullInterface, x::CategoricalArrays.CategoricalVector{String, UInt8, String, CategoricalArrays.CategoricalValue{String, UInt8}, Union{}})
    @ MLJBase ~/.julia/packages/MLJBase/swtDd/src/interface/data_utils.jl:18
 [11] int(x::CategoricalArrays.CategoricalVector{String, UInt8, String, CategoricalArrays.CategoricalValue{String, UInt8}, Union{}}; type::Nothing)
    @ MLJModelInterface ~/.julia/packages/MLJModelInterface/MqreB/src/data_utils.jl:73
 [12] int(x::CategoricalArrays.CategoricalVector{String, UInt8, String, CategoricalArrays.CategoricalValue{String, UInt8}, Union{}})
    @ MLJModelInterface ~/.julia/packages/MLJModelInterface/MqreB/src/data_utils.jl:73
 [13] fit(m::MLJDecisionTreeInterface.DecisionTreeClassifier, verbosity::Int64, X::DataFrame, y::CategoricalArrays.CategoricalVector{String, UInt8, String, CategoricalArrays.CategoricalValue{String, UInt8}, Union{}})
    @ MLJDecisionTreeInterface ~/.julia/packages/MLJDecisionTreeInterface/q546Q/src/MLJDecisionTreeInterface.jl:95
 [14] fit_only!(mach::Machine{MLJDecisionTreeInterface.DecisionTreeClassifier, true}; rows::Vector{Int64}, verbosity::Int64, force::Bool)
    @ MLJBase ~/.julia/packages/MLJBase/swtDd/src/machines.jl:470
 [15] #fit!#98
    @ ~/.julia/packages/MLJBase/swtDd/src/machines.jl:537 [inlined]
 [16] top-level scope
    @ REPL[41]:1
```

**To Reproduce**
Not sure how to reproduce. In my case it happens as I said before. I can create models without any issue. 

**Versions**
I just installed MLJ **v0.16.2** on Julia **Version 1.6.1 (2021-04-23)**. I am running Arch Linux.

**Comment by ablaom** [comment] 2021-05-02 20:09
Thanks for reporting. Duplicate of https://github.com/alan-turing-institute/MLJ.jl/issues/781 which I am sorting now.

**Closed by ablaom** 2021-05-02 20:09 UTC

**Comment by ablaom** [comment] 2021-05-02 20:11
By the way, this patch may already fix your issue https://github.com/JuliaRegistries/General/pull/35822. Try updating CategoricalArrays again.
