### ISSUE TITLE
Test MLJ 0.8

### ISSUE THREAD

**Issue by azev77** [alan-turing-institute/MLJ.jl#430] opened 2020-02-04 21:41 UTC
Today I did a fresh download of Julia 1.3.1 & MLJ, MLJLinearModels etc.
For some reason Julia doesn't download the latest version of MLJLinearModels by default. 
Instead as a default it installs an old version: MLJLinearModels v0.1.0

I tried to train all 47 regression models on the Boston housing data. 
The following models didn't work (I think mostly b/c/o MLJLinearModels):
"LassoCVRegressor","ElasticNetRegressor","HuberRegressor", "LADRegressor","QuantileRegressor","RidgeRegressor", "RobustRegressor"

**Comment by ablaom** [comment] 2020-02-06 20:31
@azev77 Thanks for that. I wonder if you could provide some detail. A stack trace and `Pkg.status(); versioninfo()` would be helpful.

**Comment by azev77** [comment] 2020-02-06 21:28
julia> Pkg.status()
    Status `C:\Users\azevelev\.julia\environments\v1.3\Project.toml`
  [c52e3926] Atom v0.11.3
  [6e4b80f9] BenchmarkTools v0.4.3
  [764a87c0] BoundaryValueDiffEq v2.4.0
  [324d7699] CategoricalArrays v0.7.7
  [9961bab8] Cbc v0.6.6
  [aaaa29a8] Clustering v0.13.3
  [861a8166] Combinatorics v1.0.0
  [a93c6f00] DataFrames v0.20.0
  [7806a523] DecisionTree v0.10.1
  [0c46a032] DifferentialEquations v6.10.1
  [31c24e10] Distributions v0.21.12
  [a3315474] EconPDEs v0.4.0
  [9d5cd8c9] FixedEffectModels v0.10.3
  [587475ba] Flux v0.10.1
  [38e38edf] GLM v1.3.6
  [60bf3e95] GLPK v0.12.1
  [2e9cd046] Gurobi v0.7.5
  [93e5fe13] Hyperopt v0.2.6
  [7073ff75] IJulia v1.21.0
  [80307280] InteractiveFixedEffectModels v0.6.2
  [b6b21f68] Ipopt v0.6.1
  [4076af6c] JuMP v0.20.1
  [e5e0dc1b] Juno v0.7.2
  [b1bec4e5] LIBSVM v0.4.0
  [add582a8] MLJ v0.8.0
  [a7f614a8] MLJBase v0.10.1
  [6ee0df7b] MLJLinearModels v0.1.0
  [d491faf4] MLJModels v0.7.2
  [6f286f6a] MultivariateStats v0.7.0
  [9bbee03b] NaiveBayes v0.4.0
  [b8a86587] NearestNeighbors v0.4.4
  [8faf48c0] NeuralNetDiffEq v1.1.0 #master (https://github.com/JuliaDiffEq/NeuralNetDiffEq.jl)
  [1dea7af3] OrdinaryDiffEq v5.28.1
  [91a5bcdd] Plots v0.28.4
  [fcd29c91] QuantEcon v0.16.2
  [ce6b1742] RDatasets v0.6.6
  [f4570300] SDDP v0.2.3 #master (https://github.com/odow/SDDP.jl.git)
  [321657f4] ScientificTypes v0.5.1
  [3646fa90] ScikitLearn v0.5.1
  [90137ffa] StaticArrays v0.12.1
  [789caeaf] StochasticDiffEq v6.19.1
  [009559a3] XGBoost v0.4.2
  [e88e6eb3] Zygote v0.4.7
  [37e2e46d] LinearAlgebra
  [10745b16] Statistics
  [8dfed614] Test


julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-1630 v3 @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)

**Comment by azev77** [comment] 2020-02-06 21:30
I don't know how to do stack trace, but the easiest way to replicate is to download a fresh Julia & Install MLJ, MLJLinearModels. 
If you get the same results as me, you will see for some reason Julia downloads an older version of MLJLinearModels by default. 

I can force a manual download of the latest version, I'm letting you know bc other users might get the same error w/o realizing the default download is not the latest version.

**Comment by ablaom** [comment] 2020-02-06 22:01
Okay, the issue is that MLJLinearModels has not updated its [compat] requirement for MLJBase, which means it is not compatible with the latest MLJ. 

The workaround is to install (in a new environment, for example) MLJLinearModels *first* and then MLJ. 

Please confirm (by closing issue) that your models work under MLJLinearModels 0.2.4, if you are able to load. 

Thanks.

**Comment by azev77** [comment] 2020-02-06 22:40
Yep. 
```Julia
rm MLJ MLJBase MLJLinearModels MLJModels ScientificTypes
add https://github.com/alan-turing-institute/MLJLinearModels.jl
add MLJ MLJBase  MLJModels ScientificTypes
#RUN All works. 
```

**Closed** 2020-02-06 22:40 UTC
