### ISSUE TITLE
Issue with Documentation/Example - DecisionTreeClassifier

### ISSUE THREAD

**Issue by pazzo83** [alan-turing-institute/MLJ.jl#126] opened 2019-05-10 20:38 UTC
Hi, I am having some trouble running the basic Iris dataset example in the main page of the docs provided.  The first issue deals with the call to the `DecisionTreeClassifier` constructor:

```
julia> tree_model = DecisionTreeClassifier(target_type=String, max_depth=2)
ERROR: MethodError: no method matching DecisionTreeClassifier(; target_type=String, max_depth=2)
Closest candidates are:
  DecisionTreeClassifier(; pruning_purity, max_depth, min_samples_leaf, min_samples_split, min_purity_increase, n_subfeatures, display_depth, post_prune, merge_purity_threshold) at /Users/christopheralexander/.julia/packages/MLJModels/OcVBr/src/DecisionTree.jl:64 got unsupported keyword argument "target_type"
  DecisionTreeClassifier(::Float64, ::Int64, ::Int64, ::Int64, ::Float64, ::Float64, ::Int64, ::Bool, ::Float64) at /Users/christopheralexander/.julia/packages/MLJModels/OcVBr/src/DecisionTree.jl:40 got unsupported keyword arguments "target_type", "max_depth"
  DecisionTreeClassifier(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at /Users/christopheralexander/.julia/packages/MLJModels/OcVBr/src/DecisionTree.jl:40 got unsupported keyword arguments "target_type", "max_depth"
Stacktrace:
 [1] kwerr(::NamedTuple{(:target_type, :max_depth),Tuple{DataType,Int64}}, ::Type) at ./error.jl:125
 [2] (::getfield(Core, Symbol("#kw#Type")))(::NamedTuple{(:target_type, :max_depth),Tuple{DataType,Int64}}, ::Type{DecisionTreeClassifier}) at ./none:0
 [3] top-level scope at none:0
```
It seems the `target_type` keyword is no longer valid to pass to this constructor.  Upon leaving it out, there is a subsequent issue when calling `predict` on the tree given a set of test data.

```
julia> yhat = predict(tree, X[test,:])
45-element Array{UnivariateFinite{CategoricalString{UInt8},Float64},1}:
 UnivariateFinite{CategoricalString{UInt8},Float64}(Dict("virginica"=>0.96875,"setosa"=>0.0,"versicolor"=>0.03125))
 UnivariateFinite{CategoricalString{UInt8},Float64}(Dict("virginica"=>0.96875,"setosa"=>0.0,"versicolor"=>0.03125))
 UnivariateFinite{CategoricalString{UInt8},Float64}(Dict("virginica"=>0.0,"setosa"=>1.0,"versicolor"=>0.0)) ...
```
Calling `misclassification_rate` yields the following:

```
julia> misclassification_rate(yhat, y[test])
1.0
```

I believe this is because yhat is that Vector of `UnivariateFinite` objects while `y[test]` is simply a `CategoricalArray`.  Is there something additional that needs to be called on `yhat` such that the proper label is selected?

**Comment by ablaom** [comment] 2019-05-12 22:45
Many thanks!

Yes, target_type has gone v0.2.0 or MLJModels. Have fixed the docs on master.

When one calls a deterministic measure (in this case misclassification_rate) on probabilistic predictions, then the intended behaviour is (at present) for modes to be automatically computed first. This did not happen here because of a bug in misclassification_rate. 

I've fixed the bug and added a test. 

BTW In the future, I suggest we either disallow calling deterministic measures on probabilistic data or issue a warning to say that this is what we are doing, yes?

**Comment by ablaom** [comment] 2019-05-12 22:45
Fixed on master

**Closed by ablaom** 2019-05-12 22:45 UTC
