### ISSUE TITLE
Migrate measures.jl to MLJBase.jl

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJ.jl#218] opened 2019-08-25 10:58 UTC
**Is your feature request related to a problem? Please describe.**
I cannot leverage MLJ measures in my packages because it is defined in the MLJ.jl top level.

**Describe the solution you'd like**
The measures.jl file could be migrated to MLJBase.jl

**Describe alternatives you've considered**
A separate package a la LossFunctions.jl could be created as a fork of LossFunctions.jl

**Additional context**
No additional context

**Comment by juliohm** [comment] 2019-08-25 11:04
This issue is similar to #208 in the sense that package features are being added to MLJ.jl instead of MLJBase.jl. Could you please consider adding these measures in MLJBase.jl instead?

Particularly, I think MLJ.jl should be a wrapper package (i.e. a project) similar to what GeoStats.jl is. Researchers who need access to the building blocks, won't depend on MLJ.jl, but on specific packages of the project.

I appreciate if you can consider the migration of the codebase whenever possible. It is becoming difficult to reuse the components externally.

**Comment by juliohm** [comment] 2019-08-25 11:16
To exemplify this common of reexporting submodules in Julia projects:

[src/DifferentialEquations.jl](https://github.com/JuliaDiffEq/DifferentialEquations.jl/blob/master/src/DifferentialEquations.jl)
[src/GeoStats.jl](https://github.com/juliohm/GeoStats.jl/blob/master/src/GeoStats.jl)

**Comment by ablaom** [comment] 2019-08-25 21:45
MLJ is already is already a "project". ML algorithms are not implemented in MLJ but external packages. I agree some MLJ functionality might gradually move out as it becomes more elaborate (eg, tuning) but it would move to new repo, not to MLJBase. MLJBase is just the model API, playing a similar role as ScitLearnBase.jl, as explained in https://github.com/alan-turing-institute/MLJBase.jl/issues/19 .

If I am implementing the MLJ interface for MyAlgorithm in MyPackage, I have no interest in measures or loading other models, and so forth. I just want the hooks on which to hang my fit and predict methods. Importing MLJBase allows me to do this.  

Closing, as essentially a duplicate of #208

**Closed by ablaom** 2019-08-25 21:45 UTC

**Comment by juliohm** [comment] 2019-08-25 22:07
@ablaom could you please reconsider this issue? I am writing validation procedures which require loss functions, and I don't want to depend on the whole MLJ.jl project to be able to reuse `rms` and other losses.

See [here](https://github.com/juliohm/GeoStatsBase.jl/blob/master/src/errors/block_cross_validation.jl#L52) and [here](https://github.com/juliohm/GeoStatsBase.jl/blob/master/src/errors/leave_ball_out.jl#L57) for two examples.

I have many other places in the codebase where losses will play an important role. Again, I cannot depend on MLJ.jl because GeoStats.jl is the equivalent project for spatial data.

**Comment by juliohm** [comment] 2019-08-25 22:14
If not MLJBase.jl, could you please consider creating a MLJLosses.jl package?

**Comment by ablaom** [comment] 2019-08-25 23:38
An MLJLosses.jl package is something we have considered. It would be good to know why you feel LossFunctions.jl is inadequate (apart from there being no `rms`- just the `L2DistLoss`). For us, one issue is that we want an API for probabilistic predictions that isn't there, and is at odds with what is there now. We would like to do things like `brier(yhat, y)` where `yhat` is a vector of `Distribution` objects, rather than point predictions. Loss functions wants a raw probability, which makes sense if all you ever to do binary classification, but which is less than ideal more generally.

**Comment by juliohm** [comment] 2019-08-25 23:43
So LossFunctions.jl will be officially supported within MLJ.jl? I wanted to
use the built-in losses because of maintenance guarantees, but if
LossFunctions.jl is preferred I can add it as a dependency in
GeoStatsBase.jl.

Ideally I wouldn't need an additional dependency and MLJBase.jl would
contain all relevant concepts in machine learning, including losses.

**Comment by ablaom** [comment] 2019-08-25 23:51
Yes, now supported on MLJ 0.3.0 ([release notes](https://github.com/alan-turing-institute/MLJ.jl/blob/master/docs/src/NEWS.md)).  

See  and https://alan-turing-institute.github.io/MLJ.jl/stable/measures/

**Comment by juliohm** [comment] 2019-08-25 23:54
I saw the announcement. Was just wondering if that is the future. I'll
depend on LossFunctions.jl meanwhile then. Thank you.
