### ISSUE TITLE
Stack of TunedModels

### ISSUE THREAD

**Issue by tpoisot** [alan-turing-institute/MLJ.jl#980] opened 2022-11-04 18:01 UTC
I am trying to apply `Stack` to a series of `TunedModel`s to a response `y` (a `CateggoricalArray` with two values, 0 and 1) and predictors `X` (a data frame with continuous variables).

The models I want to stack are `BinaryThresholdPredictor` for which I would like to optimize the threshold, so they are wrapped in a `TunedModel `. The code looks like this:

Models ->

~~~julia
Standardizer = @load Standardizer pkg = MLJModels add = true verbosity = 0
LOG = @load LogisticClassifier pkg = MLJLinearModels add = true verbosity = 0
LM = @load LinearBinaryClassifier pkg = GLM add = true verbosity = 0
LR = @load LinearRegressor pkg = MLJLinearModels add = true verbosity = 0

# Test for a stack of models
model_std_lm = BinaryThresholdPredictor(Standardizer() |> LM())
model_std_log = BinaryThresholdPredictor(Standardizer() |> LOG())
~~~

Tuned models ->

~~~julia
_args = (
    tuning=RandomSearch(rng=Xoshiro(123)),
    resampling=CV(nfolds=3, shuffle=true, rng=Xoshiro(123)),
    range=range(base_model, :threshold, lower=0.2, upper=0.8),
    measure=mcc,
    n=25
)

# Tuned models training
std_lm = TunedModel(model_std_lm; _args...)
std_lm_mach = machine(std_lm, X, y) |> fit!

std_log = TunedModel(model_std_log; _args...)
std_log_mach = machine(std_log, X, y) |> fit!
~~~

Stack -> 

~~~julia
# Make a Stack
stacked_model = Stack(
    metalearner=LM(),
    resampling=CV(nfolds=3, shuffle=true, rng=Xoshiro(123)),
    stdlm=std_lm,
    stdlog=std_log,
)
~~~

Machine + fit! ->

~~~julia
mach = machine(stacked_model, X, y)
fit!(match)
~~~

And this is when it breaks down. Specifically, it says:

~~~julia
ERROR: MethodError: no method matching pre_judge_transform(::Node{Machine{MLJTuning.DeterministicTunedModel{RandomSearch, BinaryThresholdPredictor{MLJBase.ProbabilisticPipeline{NamedTuple{(:standardizer, :linear_binary_classifier), Tuple{Unsupervised, Probabilistic}}, MLJModelInterface.predict}}}, true}}, ::Type{MLJTuning.DeterministicTunedModel{RandomSearch, BinaryThresholdPredictor{MLJBase.ProbabilisticPipeline{NamedTuple{(:standardizer, :linear_binary_classifier), Tuple{Unsupervised, Probabilistic}}, MLJModelInterface.predict}}}}, ::Type{Unknown})
~~~

I tried using different models as the metalearner, but it doesn't change the error message.

What am I doing wrong? Is `Stack` the correct way to do this, or should I be using networks?

**Comment by ablaom** [comment] 2022-11-06 20:49
Thanks for your query. 

@OlivierLabayle may want to comment, but I'm pretty sure the issue is that base learners in a `Stack` cannot be deterministic classifiers. Base learners are restricted to deterministic/probablistic regressors and probabilistic classifiers. So you could stack the unthresholded models, just fine.

**Comment by tpoisot** [comment] 2022-11-06 20:57
Gotcha. I'll try again with the un-thresholded models in the stack when I'm back at my computer.

**Comment by ablaom** [comment] 2023-02-08 02:36
Closing as apparently resolved.

**Closed by ablaom** 2023-02-08 02:36 UTC
